tag_prefix = "v"

monorepo_version_separator = "-"
generate_mono_repository_global_tag = false

ignore_merge_commits = true

branch_whitelist = ["master", "main"]

pre_bump_hooks = ["cargo check --workspace --release"]

pre_package_bump_hooks = [
  "cargo test --all-features -- --test-threads 1",
  "cargo build --release",
  "cargo fmt --all",
  "cargo set-version --package {{package}} {{version}}",
  "git add :/Cargo.lock",
]

post_bump_hooks = ["git push", "git push --tags"]

post_package_bump_hooks = ["cargo package"]

[packages.fluent-static]
path = "crates/lib"
post_bump_hooks = ["cargo publish -p fluent-static"]

[packages.fluent-static-codegen]
path = "crates/codegen"
post_bump_hooks = ["cargo publish -p fluent-static-codegen"]

[packages.fluent-static-macros]
path = "crates/macros"
post_bump_hooks = ["cargo publish -p fluent-static-macros"]

[packages.fluent-static-value]
path = "crates/value"
post_bump_hooks = ["cargo publish -p fluent-static-value"]

[packages.fluent-static-function]
path = "crates/function"
post_bump_hooks = ["cargo publish -p fluent-static-function"]

[packages.fluent-static-formatter]
path = "crates/formatter"
post_bump_hooks = ["cargo publish -p fluent-static-formatter"]

[commit_types]
bump = { changelog_title = "Dependency updates" }

[changelog]
path = "CHANGELOG.md"
remote = "github.com"
repository = "fluent-static"
owner = "zaytsev"
authors = [{ signature = "Sergey Zaytsev", username = "zaytsev" }]

[bump_profiles]
