tag_prefix = "v"
monorepo_version_separator = "-"
ignore_merge_commits = true

branch_whitelist = ["master", "main"]

pre_bump_hooks = ["cargo check --workspace --release"]

pre_package_bump_hooks = [
  "cargo test -- --test-threads 1",
  "cargo build --release",
  "cargo fmt --all",
  "cargo set-version {{version}}",
  "git add :/Cargo.lock",
]

post_bump_hooks = ["git push", "git push --tags"]

post_package_bump_hooks = ["cargo package"]

[packages.fluent-static]
path = "fluent-static"
post_bump_hooks = ["cargo publish -p fluent-static"]

[packages.fluent-static-codegen]
path = "fluent-static-codegen"
post_bump_hooks = ["cargo publish -p fluent-static-codegen"]

[commit_types]
bump = { changelog_title = "Dependency updates" }

[changelog]
path = "CHANGELOG.md"
remote = "github.com"
repository = "fluent-static"
owner = "zaytsev"
authors = [{ signature = "Sergey Zaytsev", username = "zaytsev" }]

[bump_profiles]
