tag_prefix = "v"
ignore_merge_commits = true
branch_whitelist = ["master", "main"]
pre_bump_hooks = [
  "cargo check",
  "cargo test -- --test-threads 1",
  "cargo build --release",
  "cargo fmt --all",
  "cargo set-version {{version}}",
  "git add Cargo.lock",
]

post_bump_hooks = [
  "git push",
  "git push --tags",
  "cargo package",
  "cargo publish -p fluent-static",
  "cargo publish -p fluent-static-codegen",
]

[commit_types]
bump = { changelog_title = "Dependency updates" }

[changelog]
path = "CHANGELOG.md"
remote = "github.com"
repository = "zaytsev"
owner = "fluent-static"
authors = [{ signature = "Sergey Zaytsev", username = "zaytsev" }]

[bump_profiles]
