[workspace]
members = ["axum", "simple", "procmacro"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
fluent-static = { path = "../fluent-static" }
fluent-static-codegen = { path = "../fluent-static-codegen" }
